In [7]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import time

# Set the number of articles to scrape
articles_to_scrape = 5000

# Create an empty list to store the scraped data
data = []

# Loop through pages until desired number of articles is reached
for page in range(1, (articles_to_scrape // 50) + 1):
    print('Processing page:', page)
    
    # Construct the URL for the page
    url = f'https://www.politifact.com/factchecks/list/?page={page}'

    try:
        # Get the page content
        page = requests.get(url)
    except Exception as e:
        print('Error fetching URL:', url)
        continue
    
    # Pause for a moment to avoid overwhelming the server
    time.sleep(2)
    
    # Parse the page content using BeautifulSoup
    soup = BeautifulSoup(page.text, 'html.parser')
    
    # Find all the list items containing article information
    articles = soup.find_all('li', class_='o-listicle__item')
    
    # Loop through each article
    for article in articles:
        # Extract information from the article
        statement = article.find('div', class_='m-statement__quote').text.strip()
        link = "https://www.politifact.com" + article.find('a')['href'].strip()
        date = article.find('footer').text[-14:-1].strip()
        source = article.find('div', class_='m-statement__meta').find('a').text.strip()
        label = article.find('div', attrs={'class': 'm-statement__content'}).find('img', attrs={'class': 'c-image__original'}).get('alt').strip()
        
        # Append the article information to the data list
        data.append((statement, link, date, source, label))

# Create a DataFrame from the collected data
df_fake = pd.DataFrame(data, columns=['title', 'Link', 'Date', 'Source', 'Label'])




Processing page: 1
Processing page: 2
Processing page: 3
Processing page: 4
Processing page: 5
Processing page: 6
Processing page: 7
Processing page: 8
Processing page: 9
Processing page: 10
Processing page: 11
Processing page: 12
Processing page: 13
Processing page: 14
Processing page: 15
Processing page: 16
Processing page: 17
Processing page: 18
Processing page: 19
Processing page: 20
Processing page: 21
Processing page: 22
Processing page: 23
Processing page: 24
Processing page: 25
Processing page: 26
Processing page: 27
Processing page: 28
Processing page: 29
Processing page: 30
Processing page: 31
Processing page: 32
Processing page: 33
Processing page: 34
Processing page: 35
Processing page: 36
Processing page: 37
Processing page: 38
Processing page: 39
Processing page: 40
Processing page: 41
Processing page: 42
Processing page: 43
Processing page: 44
Processing page: 45
Processing page: 46
Processing page: 47
Processing page: 48
Processing page: 49
Processing page: 50
Processin

In [8]:
df_fake

title  \
0     “WEF admits Maui wildfires orchestrated to tra...   
1     La vacuna contra COVID-19 "contiene óxido de g...   
2     “Michelle Obama finally responds to Obama’s hi...   
3     “A higher percentage of American workers are w...   
4     "Hawaii is being attacked by direct energy wea...   
...                                                 ...   
2995  “Australia to Implement Quarantine Camps for t...   
2996  Terry McAuliffe has a campaign sign that says,...   
2997  “The nation reported adding 194,000 jobs in Se...   
2998  “COP26 luxury EVs to be recharged using diesel...   
2999  The remains of Brian Laundrie that were discov...   

                                                   Link           Date  \
0     https://www.politifact.com/personalities/faceb...  gust 22, 2023   
1     https://www.politifact.com/personalities/faceb...  gust 22, 2023   
2     https://www.politifact.com/personalities/faceb...  gust 21, 2023   
3     https://www.politifact.com/personalities/joe-b...  gust 21, 2023   
4     https://www.politifact.com/personalities/insta...  gust 18, 2023   
...                                                 ...            ...   
2995  https://www.politifact.com/personalities/charl...  ober 27, 2021   
2996  https://www.politifact.com/personalities/viral...  ober 27, 2021   
2997  https://www.politifact.com/personalities/ron-d...  ober 27, 2021   
2998  https://www.politifact.com/personalities/blog-...  ober 26, 2021   
2999  https://www.politifact.com/personalities/faceb...  ober 26, 2021   

                     Source        Label  
0            Facebook posts        false  
1            Facebook posts        false  
2            Facebook posts   pants-fire  
3                 Joe Biden  barely-true  
4           Instagram posts        false  
...                     ...          ...  
2995  The Charlie Kirk Show        false  
2996            Viral image        false  
2997           Ron DeSantis    half-true  
2998               Bloggers  barely-true  
2999         Facebook posts        false  

[3000 rows x 5 columns]

In [14]:
df_fake['label'] = 0
df_fake = df_fake[['title', 'label' ]]

In [22]:
df_fake_All = df_fake.copy()

In [25]:
df_fake = df_fake.head(1000)

In [26]:
df_fake.shape

(1000, 2)

In [12]:
import feedparser as fp
import newspaper
from newspaper import Article
from datetime import datetime
import pandas as pd

# Dictionary of news sites
sites = {
    "cnn": {
        "link": "http://edition.cnn.com/"
    },
    "bbc": {
        "rss": "http://feeds.bbci.co.uk/news/rss.xml",
        "link": "http://www.bbc.com/"
    },
    "theguardian": {
        "rss": "https://www.theguardian.com/uk/rss",
        "link": "https://www.theguardian.com/international"
    },
    "breitbart": {
        "link": "http://www.breitbart.com/"
    },
    "infowars": {
        "link": "https://www.infowars.com/"
    },
    "foxnews": {
        "link": "http://www.foxnews.com/"
    },
    "nbcnews": {
        "link": "http://www.nbcnews.com/"
    },
    "washingtonpost": {
        "rss": "http://feeds.washingtonpost.com/rss/world",
        "link": "https://www.washingtonpost.com/"
    },
    "theonion": {
        "link": "http://www.theonion.com/"
    }
}

LIMIT = 3000
data = []
from time import mktime

# Now you can use the mktime function


# Iterate through each news company
for site, info in sites.items():
    print("Scraping articles from", site)

    if 'rss' in info:
        d = fp.parse(info['rss'])
        for entry in d.entries:
            if len(data) >= LIMIT:
                break
            if hasattr(entry, 'published'):
                article = {
                    'site': site,
                    'link': entry.link,
                    'published': datetime.fromtimestamp(mktime(entry.published_parsed)).isoformat()
                }
                try:
                    content = Article(entry.link)
                    content.download()
                    content.parse()
                    article['title'] = content.title
                    article['text'] = content.text
                    data.append(article)
                except Exception as e:
                    print(e, "continuing...")
                    continue
    else:
        paper = newspaper.build(info['link'], memoize_articles=False)
        for content in paper.articles:
            if len(data) >= LIMIT:
                break
            try:
                content.download()
                content.parse()
            except Exception as e:
                print(e, "continuing...")
                continue
            if content.publish_date is None:
                continue
            article = {
                'site': site,
                'title': content.title,
                'text': content.text,
                'link': content.url,
                'published': content.publish_date.isoformat()
            }
            data.append(article)

# Create DataFrame
df_real = pd.DataFrame(data)

Scraping articles from cnn
Article `download()` failed with HTTPSConnectionPool(host='edition.cnn.com', port=443): Max retries exceeded with url: /2023/08/22/world/chandrayaan-3-landing-photos-india-scn/index.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x123743640>, 'Connection to edition.cnn.com timed out. (connect timeout=7)')) on URL http://edition.cnn.com/2023/08/22/world/chandrayaan-3-landing-photos-india-scn/index.html continuing...
Article `download()` failed with HTTPSConnectionPool(host='edition.cnn.com', port=443): Max retries exceeded with url: /2023/08/19/politics/ron-desantis-debate-strategy-2024/index.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10862a140>, 'Connection to edition.cnn.com timed out. (connect timeout=7)')) on URL http://edition.cnn.com/2023/08/19/politics/ron-desantis-debate-strategy-2024/index.html continuing...
Article `download()` failed with 404 Client Error: Not Found for url:

In [21]:
df_real.shape

(1053, 5)

In [27]:
df_real['label'] = 1 
df_real = df_real[["title","label"]]
df_real

title  label
0     Pakistan cable car: All 8 people rescued from ...      1
1                   Why Republican voters believe Trump      1
2     ‘Silence is killing me:’ A firefighter on Ukra...      1
3     BRICS Summit: Who stands to benefit from Russi...      1
4     Women’s World Cup: The image that epitomizes a...      1
...                                                 ...    ...
1048  Breaking news and latest headlines, U.S. news,...      1
1049  Breaking news and latest headlines, U.S. news,...      1
1050  Breaking news and latest headlines, U.S. news,...      1
1051  Ukraine live briefing: Kyiv to get F-16 fighte...      1
1052  Breaking news and latest headlines, U.S. news,...      1

[1053 rows x 2 columns]

In [28]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import string as st
import re
import nltk
from nltk import PorterStemmer, WordNetLemmatizer
import matplotlib.pyplot as plt

In [29]:
data = pd.concat([df_real, df_fake])

In [32]:
data['label'].value_counts()

1    1053
0    1000
Name: label, dtype: int64

# Text cleaning and processing steps-
* Remove punctuations
* Convert text to tokens
* Remove tokens of length less than or equal to 3
* Remove stopwords using NLTK corpus stopwords list to match
* Apply stemming
* Apply lemmatization
* Convert words to feature vectors

In [34]:
# Remove all punctuations from the text

def remove_punct(text):
    return ("".join([ch for ch in text if ch not in st.punctuation]))

In [35]:
data['removed_punc'] = data['title'].apply(lambda x: remove_punct(x))
data.head()

title  label  \
0  Pakistan cable car: All 8 people rescued from ...      1   
1                Why Republican voters believe Trump      1   
2  ‘Silence is killing me:’ A firefighter on Ukra...      1   
3  BRICS Summit: Who stands to benefit from Russi...      1   
4  Women’s World Cup: The image that epitomizes a...      1   

                                        removed_punc  
0  Pakistan cable car All 8 people rescued from s...  
1                Why Republican voters believe Trump  
2  ‘Silence is killing me’ A firefighter on Ukrai...  
3  BRICS Summit Who stands to benefit from Russia...  
4  Women’s World Cup The image that epitomizes a ...

In [36]:
''' Convert text to lower case tokens. Here, split() is applied on white-spaces. But, it could be applied
    on special characters, tabs or any other string based on which text is to be seperated into tokens.
'''
def tokenize(text):
    text = re.split('\s+' ,text)
    return [x.lower() for x in text]

In [37]:
data['tokens'] = data['removed_punc'].apply(lambda msg : tokenize(msg))
data.head()

title  label  \
0  Pakistan cable car: All 8 people rescued from ...      1   
1                Why Republican voters believe Trump      1   
2  ‘Silence is killing me:’ A firefighter on Ukra...      1   
3  BRICS Summit: Who stands to benefit from Russi...      1   
4  Women’s World Cup: The image that epitomizes a...      1   

                                        removed_punc  \
0  Pakistan cable car All 8 people rescued from s...   
1                Why Republican voters believe Trump   
2  ‘Silence is killing me’ A firefighter on Ukrai...   
3  BRICS Summit Who stands to benefit from Russia...   
4  Women’s World Cup The image that epitomizes a ...   

                                              tokens  
0  [pakistan, cable, car, all, 8, people, rescued...  
1          [why, republican, voters, believe, trump]  
2  [‘silence, is, killing, me’, a, firefighter, o...  
3  [brics, summit, who, stands, to, benefit, from...  
4  [women’s, world, cup, the, image, that, epitom...

In [38]:
# Remove tokens of length less than 3
def remove_small_words(text):
    return [x for x in text if len(x) > 3 ]

In [39]:
data['larger_tokens'] = data['tokens'].apply(lambda x : remove_small_words(x))
data.head()

title  label  \
0  Pakistan cable car: All 8 people rescued from ...      1   
1                Why Republican voters believe Trump      1   
2  ‘Silence is killing me:’ A firefighter on Ukra...      1   
3  BRICS Summit: Who stands to benefit from Russi...      1   
4  Women’s World Cup: The image that epitomizes a...      1   

                                        removed_punc  \
0  Pakistan cable car All 8 people rescued from s...   
1                Why Republican voters believe Trump   
2  ‘Silence is killing me’ A firefighter on Ukrai...   
3  BRICS Summit Who stands to benefit from Russia...   
4  Women’s World Cup The image that epitomizes a ...   

                                              tokens  \
0  [pakistan, cable, car, all, 8, people, rescued...   
1          [why, republican, voters, believe, trump]   
2  [‘silence, is, killing, me’, a, firefighter, o...   
3  [brics, summit, who, stands, to, benefit, from...   
4  [women’s, world, cup, the, image, that, epitom...   

                                       larger_tokens  
0  [pakistan, cable, people, rescued, from, stran...  
1               [republican, voters, believe, trump]  
2  [‘silence, killing, firefighter, ukraine’s, fr...  
3  [brics, summit, stands, benefit, from, russiaf...  
4  [women’s, world, image, that, epitomizes, tran...

In [40]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/niteshchandra/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [41]:
''' Remove stopwords. Here, NLTK corpus list is used for a match. However, a customized user-defined 
    list could be created and used to limit the matches in input text. 
'''
def remove_stopwords(text):
    return [word for word in text if word not in nltk.corpus.stopwords.words('english')]

In [42]:
data['clean_tokens'] = data['larger_tokens'].apply(lambda x : remove_stopwords(x))
data.head()

title  label  \
0  Pakistan cable car: All 8 people rescued from ...      1   
1                Why Republican voters believe Trump      1   
2  ‘Silence is killing me:’ A firefighter on Ukra...      1   
3  BRICS Summit: Who stands to benefit from Russi...      1   
4  Women’s World Cup: The image that epitomizes a...      1   

                                        removed_punc  \
0  Pakistan cable car All 8 people rescued from s...   
1                Why Republican voters believe Trump   
2  ‘Silence is killing me’ A firefighter on Ukrai...   
3  BRICS Summit Who stands to benefit from Russia...   
4  Women’s World Cup The image that epitomizes a ...   

                                              tokens  \
0  [pakistan, cable, car, all, 8, people, rescued...   
1          [why, republican, voters, believe, trump]   
2  [‘silence, is, killing, me’, a, firefighter, o...   
3  [brics, summit, who, stands, to, benefit, from...   
4  [women’s, world, cup, the, image, that, epitom...   

                                       larger_tokens  \
0  [pakistan, cable, people, rescued, from, stran...   
1               [republican, voters, believe, trump]   
2  [‘silence, killing, firefighter, ukraine’s, fr...   
3  [brics, summit, stands, benefit, from, russiaf...   
4  [women’s, world, image, that, epitomizes, tran...   

                                        clean_tokens  
0  [pakistan, cable, people, rescued, stranded, c...  
1               [republican, voters, believe, trump]  
2  [‘silence, killing, firefighter, ukraine’s, fr...  
3  [brics, summit, stands, benefit, russiafriendl...  
4  [women’s, world, image, epitomizes, transforma...

### Apply stemming to convert tokens to their root form. This is a rule-based process of word form conversion where word-suffixes are truncated irrespective of whether the root word is an actual word in the language dictionary. 



In [43]:
# Apply stemming to get root words 
def stemming(text):
    ps = PorterStemmer()
    return [ps.stem(word) for word in text]

In [44]:
data['stem_words'] = data['clean_tokens'].apply(lambda wrd: stemming(wrd))
data.head()

title  label  \
0  Pakistan cable car: All 8 people rescued from ...      1   
1                Why Republican voters believe Trump      1   
2  ‘Silence is killing me:’ A firefighter on Ukra...      1   
3  BRICS Summit: Who stands to benefit from Russi...      1   
4  Women’s World Cup: The image that epitomizes a...      1   

                                        removed_punc  \
0  Pakistan cable car All 8 people rescued from s...   
1                Why Republican voters believe Trump   
2  ‘Silence is killing me’ A firefighter on Ukrai...   
3  BRICS Summit Who stands to benefit from Russia...   
4  Women’s World Cup The image that epitomizes a ...   

                                              tokens  \
0  [pakistan, cable, car, all, 8, people, rescued...   
1          [why, republican, voters, believe, trump]   
2  [‘silence, is, killing, me’, a, firefighter, o...   
3  [brics, summit, who, stands, to, benefit, from...   
4  [women’s, world, cup, the, image, that, epitom...   

                                       larger_tokens  \
0  [pakistan, cable, people, rescued, from, stran...   
1               [republican, voters, believe, trump]   
2  [‘silence, killing, firefighter, ukraine’s, fr...   
3  [brics, summit, stands, benefit, from, russiaf...   
4  [women’s, world, image, that, epitomizes, tran...   

                                        clean_tokens  \
0  [pakistan, cable, people, rescued, stranded, c...   
1               [republican, voters, believe, trump]   
2  [‘silence, killing, firefighter, ukraine’s, fr...   
3  [brics, summit, stands, benefit, russiafriendl...   
4  [women’s, world, image, epitomizes, transforma...   

                                          stem_words  
0  [pakistan, cabl, peopl, rescu, strand, cabl, h...  
1                 [republican, voter, believ, trump]  
2  [‘silenc, kill, firefight, ukraine’, frontlin,...  
3  [bric, summit, stand, benefit, russiafriendli,...  
4  [women’, world, imag, epitom, transform, tourn...

### Lemmatization converts word to it's dictionary base form. This process takes language grammar and vocabulary into consideration while conversion. Hence, it is different from Stemming in that it does not merely truncate the suffixes to get the root word.


In [45]:
# Apply lemmatization on tokens
def lemmatize(text):
    word_net = WordNetLemmatizer()
    return [word_net.lemmatize(word) for word in text]

In [46]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/niteshchandra/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [47]:
data['lemma_words'] = data['clean_tokens'].apply(lambda x : lemmatize(x))
data.head()

title  label  \
0  Pakistan cable car: All 8 people rescued from ...      1   
1                Why Republican voters believe Trump      1   
2  ‘Silence is killing me:’ A firefighter on Ukra...      1   
3  BRICS Summit: Who stands to benefit from Russi...      1   
4  Women’s World Cup: The image that epitomizes a...      1   

                                        removed_punc  \
0  Pakistan cable car All 8 people rescued from s...   
1                Why Republican voters believe Trump   
2  ‘Silence is killing me’ A firefighter on Ukrai...   
3  BRICS Summit Who stands to benefit from Russia...   
4  Women’s World Cup The image that epitomizes a ...   

                                              tokens  \
0  [pakistan, cable, car, all, 8, people, rescued...   
1          [why, republican, voters, believe, trump]   
2  [‘silence, is, killing, me’, a, firefighter, o...   
3  [brics, summit, who, stands, to, benefit, from...   
4  [women’s, world, cup, the, image, that, epitom...   

                                       larger_tokens  \
0  [pakistan, cable, people, rescued, from, stran...   
1               [republican, voters, believe, trump]   
2  [‘silence, killing, firefighter, ukraine’s, fr...   
3  [brics, summit, stands, benefit, from, russiaf...   
4  [women’s, world, image, that, epitomizes, tran...   

                                        clean_tokens  \
0  [pakistan, cable, people, rescued, stranded, c...   
1               [republican, voters, believe, trump]   
2  [‘silence, killing, firefighter, ukraine’s, fr...   
3  [brics, summit, stands, benefit, russiafriendl...   
4  [women’s, world, image, epitomizes, transforma...   

                                          stem_words  \
0  [pakistan, cabl, peopl, rescu, strand, cabl, h...   
1                 [republican, voter, believ, trump]   
2  [‘silenc, kill, firefight, ukraine’, frontlin,...   
3  [bric, summit, stand, benefit, russiafriendli,...   
4  [women’, world, imag, epitom, transform, tourn...   

                                         lemma_words  
0  [pakistan, cable, people, rescued, stranded, c...  
1                [republican, voter, believe, trump]  
2  [‘silence, killing, firefighter, ukraine’s, fr...  
3  [brics, summit, stand, benefit, russiafriendly...  
4  [women’s, world, image, epitomizes, transforma...

In [48]:
# Create sentences to get clean text as input for vectors

def return_sentences(tokens):
    return " ".join([word for word in tokens])

In [49]:
data['clean_text'] = data['lemma_words'].apply(lambda x : return_sentences(x))
data.head()

title  label  \
0  Pakistan cable car: All 8 people rescued from ...      1   
1                Why Republican voters believe Trump      1   
2  ‘Silence is killing me:’ A firefighter on Ukra...      1   
3  BRICS Summit: Who stands to benefit from Russi...      1   
4  Women’s World Cup: The image that epitomizes a...      1   

                                        removed_punc  \
0  Pakistan cable car All 8 people rescued from s...   
1                Why Republican voters believe Trump   
2  ‘Silence is killing me’ A firefighter on Ukrai...   
3  BRICS Summit Who stands to benefit from Russia...   
4  Women’s World Cup The image that epitomizes a ...   

                                              tokens  \
0  [pakistan, cable, car, all, 8, people, rescued...   
1          [why, republican, voters, believe, trump]   
2  [‘silence, is, killing, me’, a, firefighter, o...   
3  [brics, summit, who, stands, to, benefit, from...   
4  [women’s, world, cup, the, image, that, epitom...   

                                       larger_tokens  \
0  [pakistan, cable, people, rescued, from, stran...   
1               [republican, voters, believe, trump]   
2  [‘silence, killing, firefighter, ukraine’s, fr...   
3  [brics, summit, stands, benefit, from, russiaf...   
4  [women’s, world, image, that, epitomizes, tran...   

                                        clean_tokens  \
0  [pakistan, cable, people, rescued, stranded, c...   
1               [republican, voters, believe, trump]   
2  [‘silence, killing, firefighter, ukraine’s, fr...   
3  [brics, summit, stands, benefit, russiafriendl...   
4  [women’s, world, image, epitomizes, transforma...   

                                          stem_words  \
0  [pakistan, cabl, peopl, rescu, strand, cabl, h...   
1                 [republican, voter, believ, trump]   
2  [‘silenc, kill, firefight, ukraine’, frontlin,...   
3  [bric, summit, stand, benefit, russiafriendli,...   
4  [women’, world, imag, epitom, transform, tourn...   

                                         lemma_words  \
0  [pakistan, cable, people, rescued, stranded, c...   
1                [republican, voter, believe, trump]   
2  [‘silence, killing, firefighter, ukraine’s, fr...   
3  [brics, summit, stand, benefit, russiafriendly...   
4  [women’s, world, image, epitomizes, transforma...   

                                          clean_text  
0  pakistan cable people rescued stranded cable h...  
1                     republican voter believe trump  
2  ‘silence killing firefighter ukraine’s frontli...  
3  brics summit stand benefit russiafriendly bloc...  
4  women’s world image epitomizes transformative ...

In [50]:
data['label'].value_counts()

1    1053
0    1000
Name: label, dtype: int64

In [51]:
final_data = data[['clean_text', 'label']]

In [52]:
final_data

clean_text  label
0    pakistan cable people rescued stranded cable h...      1
1                       republican voter believe trump      1
2    ‘silence killing firefighter ukraine’s frontli...      1
3    brics summit stand benefit russiafriendly bloc...      1
4    women’s world image epitomizes transformative ...      1
..                                                 ...    ...
995       “for last several month wage gone price gone      0
996  federal reserve “has suspended availability cu...      0
997  biden’s billion union pension fund “the larges...      0
998  “the virginia education agenda would erase sla...      0
999  large machinery “required move 500000 pound ea...      0

[2053 rows x 2 columns]

### TF-IDF : Term Frequency - Inverse Document Frequency
#### The term frequency is the number of times a term occurs in a document. Inverse document frequency is an inverse function of the number of documents in which   that a given word occurs.
#### The product of these two terms gives tf-idf weight for a word in the corpus. The higher the frequency of occurrence of a word, lower is it's weight and vice-versa. This gives more weightage to rare terms in the corpus and penalizes more commonly occuring terms.
#### Other widely used vectorizer is Count vectorizer which only considers the frequency of occurrence of a word across the corpus.


In [54]:
# Split data in to training, testing sets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

text_train, text_test, y_train, y_test = train_test_split(data['clean_text'], data['label'], test_size = 0.3)
print(text_train.shape)
print(text_test.shape)

(1437,)
(616,)


In [55]:
y_train.value_counts()

1    734
0    703
Name: label, dtype: int64

In [56]:
# Convert lemmatized words to Tf-Idf feature vectors
np.set_printoptions(threshold=2)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_train = tfidf.fit_transform(text_train)
X_test = tfidf.transform(text_test)
print(X_train.toarray())
print(X_train.shape)
print(X_test.toarray())
print(X_test.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(1437, 4650)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(616, 4650)


In [61]:
# 1st Model - KNN

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

print('KNN model fitted..')
pred = knn.predict(X_test)
print("Accuracy score : {}".format(accuracy_score(y_test, pred)))
print("Confusion matrix : \n {}".format(confusion_matrix(y_test, pred)))

KNN model fitted..
Accuracy score : 0.7743506493506493
Confusion matrix : 
 [[240  57]
 [ 82 237]]


In [59]:
# 2nd Model - Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

print('Random Forest Classifier model fitted..')
pred = rf.predict(X_test)
print("Accuracy score : {}".format(accuracy_score(y_test, pred)))
print("Confusion matrix : \n {}".format(confusion_matrix(y_test, pred)))

Random Forest Classifier model fitted..
Accuracy score : 0.8311688311688312
Confusion matrix : 
 [[212  85]
 [ 19 300]]


In [66]:
#3rd Model - Logistic Regression

from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
reg.fit(X_train, y_train)


print('Logistic Regression Classifier model fitted..')
pred = reg.predict(X_test)
print("Accuracy score : {}".format(accuracy_score(y_test, pred)))
print("Confusion matrix : \n {}".format(confusion_matrix(y_test, pred)))

Logistic Regression Classifier model fitted..
Accuracy score : 0.8814935064935064
Confusion matrix : 
 [[257  40]
 [ 33 286]]


In [67]:
#4th Model - Decision Tree

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

print('Decision Tree model fitted..')
pred = dtc.predict(X_test)
print("Accuracy score : {}".format(accuracy_score(y_test, pred)))
print("Confusion matrix : \n {}".format(confusion_matrix(y_test, pred)))

Decision Tree model fitted..
Accuracy score : 0.823051948051948
Confusion matrix : 
 [[216  81]
 [ 28 291]]


In [68]:
#5th Model - Support Vector Machine

from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)


print('SVM Classifier model fitted..')
pred = svc.predict(X_test)
print("Accuracy score : {}".format(accuracy_score(y_test, pred)))
print("Confusion matrix : \n {}".format(confusion_matrix(y_test, pred)))

SVM Classifier model fitted..
Accuracy score : 0.900974025974026
Confusion matrix : 
 [[286  11]
 [ 50 269]]


In [69]:
k = tfidf.transform(["Capital Punishment For Mob Lynching: Big Revamp Of Indian Criminal Laws"]).toarray()
print(svc.predict(k) > 0.5 )

[False]


# gfef
## heff

In [72]:
import pickle

pickle.dump(tfidf, open("../models/tfidf.pkl", "wb"))
pickle.dump(rf, open("../models/rf.pkl", "wb"))
pickle.dump(svc, open("../models/svm.pkl", "wb"))

In [75]:
vec = pickle.load(open("../models/tfidf.pkl",'rb'))
svm =  pickle.load(open("../models/svm.pkl",'rb'))

In [151]:
old = pickle.load(open("/Users/niteshchandra/Desktop/rf.pkl", 'rb'))
old_tfidf = pickle.load(open("/Users/niteshchandra/Desktop/tfidf.pkl", 'rb'))

In [202]:
str1 =  "Back 'Chandamama ek tour ke…: PM Modi hails Indias landing on Moon, joins from South Africa"

In [203]:
feature = vec.transform([str1]).toarray()
F = old_tfidf.transform([str1]).toarray()

In [204]:
print(" SVM MODEL RESULT - {}".format(svm.predict(feature) > 0.5) )
print(" RF MODEL RESULT - {}".format(rf.predict(feature) > 0.5) )
print(" DTC MODEL RESULT - {}".format(dtc.predict(feature) > 0.5) )
print(" Logistic reg MODEL RESULT - {}".format(reg.predict(feature) > 0.5) )
print(" KNN MODEL RESULT - {}".format(knn.predict(feature) > 0.5) )
print(" OLD MODEL RESULT - {}".format(old.predict(F) > 0.5) )

 SVM MODEL RESULT - [ True]
 RF MODEL RESULT - [ True]
 DTC MODEL RESULT - [ True]
 Logistic reg MODEL RESULT - [ True]
 KNN MODEL RESULT - [False]
 OLD MODEL RESULT - [ True]


In [ ]:
#RF And DTC Pridicting better
# RF - 3
# DTC - 2
# KNN - 1
